import type { Role } from "@prisma/client";

export const permissions = {
  CREATE_TENDER: "CREATE_TENDER",
  UPLOAD_TENDER_DOCUMENT: "UPLOAD_TENDER_DOCUMENT",
  CREATE_TENDER_VERSION: "CREATE_TENDER_VERSION",
  SUBMIT_TENDER_AMENDMENT: "SUBMIT_TENDER_AMENDMENT",
  SUBMIT_BID: "SUBMIT_BID",
  VIEW_ELIGIBLE_TENDERS: "VIEW_ELIGIBLE_TENDERS",
  APPROVE_EVALUATION: "APPROVE_EVALUATION",
  REJECT_EVALUATION: "REJECT_EVALUATION",
  VIEW_ASSIGNED_TENDERS: "VIEW_ASSIGNED_TENDERS",
  APPROVE_PAYMENT: "APPROVE_PAYMENT",
  REJECT_PAYMENT: "REJECT_PAYMENT",
  VIEW_FINANCE_QUEUE: "VIEW_FINANCE_QUEUE",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  VERIFY_PROCUREMENT_HISTORY: "VERIFY_PROCUREMENT_HISTORY",
  VERIFY_DOCUMENT: "VERIFY_DOCUMENT",
  VIEW_BLOCKCHAIN_PROOFS: "VIEW_BLOCKCHAIN_PROOFS",
  VIEW_ROLE_ACTION_HISTORY: "VIEW_ROLE_ACTION_HISTORY",
  COMPLETE_PROCUREMENT: "COMPLETE_PROCUREMENT",
  CANCEL_TENDER: "CANCEL_TENDER",
  MANAGE_TENDER_ASSIGNMENTS: "MANAGE_TENDER_ASSIGNMENTS",
  CREATE_TENDER_MANIFEST: "CREATE_TENDER_MANIFEST",
  REQUEST_PUBLICATION_APPROVAL: "REQUEST_PUBLICATION_APPROVAL",
  APPROVE_TENDER_PUBLICATION: "APPROVE_TENDER_PUBLICATION",
  SUBMIT_PROPOSAL_PACKAGE: "SUBMIT_PROPOSAL_PACKAGE",
  COMMIT_PROPOSAL_ENVELOPE: "COMMIT_PROPOSAL_ENVELOPE",
  CLOSE_TENDER: "CLOSE_TENDER",
  REQUEST_KEY_RELEASE: "REQUEST_KEY_RELEASE",
  RELEASE_ENVELOPE_KEY: "RELEASE_ENVELOPE_KEY",
  DECLARE_CONFLICT_OF_INTEREST: "DECLARE_CONFLICT_OF_INTEREST",
  SUBMIT_EVALUATION_REPORT: "SUBMIT_EVALUATION_REPORT",
  SUBMIT_AWARD_RECOMMENDATION: "SUBMIT_AWARD_RECOMMENDATION",
  APPROVE_AWARD: "APPROVE_AWARD",
  COMMIT_CONTRACT_HASH: "COMMIT_CONTRACT_HASH",
  ARCHIVE_TENDER: "ARCHIVE_TENDER",
  MANAGE_LEGACY_EGP_SIMULATOR: "MANAGE_LEGACY_EGP_SIMULATOR",
  VIEW_PUBLIC_AUDIT_PROOFS: "VIEW_PUBLIC_AUDIT_PROOFS"
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];

export const rolePermissions: Record<Role, Permission[]> = {
  PROCUREMENT_OFFICER: [
    permissions.CREATE_TENDER,
    permissions.CREATE_TENDER_MANIFEST,
    permissions.REQUEST_PUBLICATION_APPROVAL,
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.UPLOAD_TENDER_DOCUMENT,
    permissions.CREATE_TENDER_VERSION,
    permissions.SUBMIT_TENDER_AMENDMENT,
    permissions.MANAGE_TENDER_ASSIGNMENTS,
    permissions.CLOSE_TENDER,
    permissions.COMMIT_CONTRACT_HASH,
    permissions.ARCHIVE_TENDER,
    permissions.MANAGE_LEGACY_EGP_SIMULATOR,
    permissions.CANCEL_TENDER
  ],
  VENDOR: [
    permissions.SUBMIT_BID,
    permissions.SUBMIT_PROPOSAL_PACKAGE,
    permissions.COMMIT_PROPOSAL_ENVELOPE,
    permissions.VIEW_ELIGIBLE_TENDERS
  ],
  EVALUATOR: [
    permissions.APPROVE_EVALUATION,
    permissions.REJECT_EVALUATION,
    permissions.VIEW_ASSIGNED_TENDERS
  ],
  FINANCE_OFFICER: [
    permissions.APPROVE_PAYMENT,
    permissions.REJECT_PAYMENT,
    permissions.VIEW_FINANCE_QUEUE,
    permissions.COMPLETE_PROCUREMENT
  ],
  AUDITOR: [
    permissions.VIEW_AUDIT_LOGS,
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.VERIFY_PROCUREMENT_HISTORY,
    permissions.VERIFY_DOCUMENT,
    permissions.VIEW_BLOCKCHAIN_PROOFS,
    permissions.VIEW_ROLE_ACTION_HISTORY,
    permissions.VIEW_PUBLIC_AUDIT_PROOFS
  ],
  TEC_MEMBER: [
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.DECLARE_CONFLICT_OF_INTEREST,
    permissions.REQUEST_KEY_RELEASE,
    permissions.SUBMIT_EVALUATION_REPORT,
    permissions.VIEW_BLOCKCHAIN_PROOFS
  ],
  TEC_CHAIR: [
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.DECLARE_CONFLICT_OF_INTEREST,
    permissions.REQUEST_KEY_RELEASE,
    permissions.RELEASE_ENVELOPE_KEY,
    permissions.SUBMIT_EVALUATION_REPORT,
    permissions.SUBMIT_AWARD_RECOMMENDATION,
    permissions.VIEW_BLOCKCHAIN_PROOFS
  ],
  APPROVING_OFFICER: [
    permissions.APPROVE_TENDER_PUBLICATION,
    permissions.APPROVE_AWARD,
    permissions.COMMIT_CONTRACT_HASH,
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.VIEW_BLOCKCHAIN_PROOFS
  ],
  FINANCIAL_INSTITUTION_OFFICER: [
    permissions.VIEW_ASSIGNED_TENDERS,
    permissions.DECLARE_CONFLICT_OF_INTEREST,
    permissions.REQUEST_KEY_RELEASE,
    permissions.RELEASE_ENVELOPE_KEY,
    permissions.SUBMIT_EVALUATION_REPORT,
    permissions.VIEW_BLOCKCHAIN_PROOFS
  ]
};

export type AuthenticatedUser = {
  userId: string;
  profileId: string;
  holderDID: string;
  employmentId: string;
  employeeHash: string;
  employer: string;
  position: string;
  employmentType: string;
  role: Role;
  permissions: Permission[];
};
